apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-byhshllt
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/go-byhshllt:azure-ea994dd78cb348678f53615e1d41aa19966c399c
          name: container-image
